### ISSUE TITLE
Possible to use client id / secret?

### ISSUE THREAD

**Issue by mirzaciri** [alexandramartinez/github-actions#4]
https://github.com/alexandramartinez/github-actions/blob/aab5dcad31b53d3acbf629035b120c4c44bf4a48/.github/workflows/build.yml#L84

As more and more organizations need to move to 2FA in Anypoint platform, there is a recommendation to use "Connected Apps".

How can we change this to utilize that instead?

I see that it should be possible when specifying it in the pom.xml file
https://docs.mulesoft.com/mule-runtime/4.4/deploy-to-cloudhub#cloudhub-deploy-reference

Also on another note, shouldn't it be possible to deploy without the need to specify it on the pom.xml file?
It is strange to specify such things directly in the application it self.

**Comment by mirzaciri** [comment]
`
<connectedAppClientId>${anypoint.client_id}</connectedAppClientId>
<connectedAppClientSecret>${anypoint.client_secret}</connectedAppClientSecret>
<connectedAppGrantType>client_credentials</connectedAppGrantType>
`

Maybe something like this would work.

**Comment by alexandramartinez** [comment]
hey thanks for the suggestion! This will be a future blog post, actually :D stay tuned!

**Comment by rmcelroy-hylaine** [comment]
@alexandramartinez it looks like you compelted this blog post and resolved this issue.

Suggestion - I wouldn't include (even a fake) client secret in the blog post. You may want to update it to be blurred or something along those lines.

This has been insanely helpful btw - haven't implemented it yet but seems very promising. Thanks!

**Comment by alexandramartinez** [comment]
@rmcelroy-hylaine A lot of people prefer to see how the credentials look like so they can see they're on the right track. I use free accounts that stop working after 30 days and edit the credentials a bit. But thank you for the suggestion! Security first :D 

I hope you find it useful :)

**Comment by alexandramartinez** [comment]
Client ID + Client Secret auth can be found here: https://github.com/alexandramartinez/github-actions/tree/connected-app
